[package]
name = "openxr-sys"
description = "OpenXR FFI bindings"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
categories = ["external-ffi-bindings", "rendering"]
keywords = ["openxr", "vr"]
license = "MIT/Apache-2.0"
edition = "2018"

[features]
d3d = []
prototypes = []

[dependencies]
ash = { version = "0.27", optional = true }
x11 = { version = "2.18", optional = true }
x11-dl = { version = "2.18", optional = true }
libc = { version = "0.2.50", optional = true }
