[package]
name = "openxr-sys"
description = "OpenXR FFI bindings"
repository = "https://github.com/Ralith/openxrs"
version = "0.1.2"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
categories = ["external-ffi-bindings", "rendering"]
keywords = ["openxr", "vr"]
license = "MIT/Apache-2.0"
edition = "2018"

[badges]
maintenance = { status = "experimental" }

[features]
prototypes = []
opengl = []
x11 = []

[dependencies]
ash = { version = "0.27", optional = true }
libc = { version = "0.2.50", optional = true }

[package.metadata.docs.rs]
all-features = true
