[package]
name = "openxr-sys"
description = "OpenXR FFI bindings"
repository = "https://github.com/Ralith/openxrs"
version = "0.1.5"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
categories = ["external-ffi-bindings", "rendering"]
keywords = ["openxr", "vr"]
license = "MIT/Apache-2.0"
edition = "2018"

[badges]
maintenance = { status = "experimental" }

[features]
prototypes = []
vulkan = ["ash"]
opengl = []
xlib = []
xcb = []
static = ["cmake", "prototypes"]
default = ["vulkan", "opengl", "xlib"]

[dependencies]
ash = { version = "0.27", optional = true }
libc = "0.2.50"

[build-dependencies]
cmake = { version = "0.1.35", optional = true }

[package.metadata.docs.rs]
features = ["prototypes", "vulkan", "opengl", "xlib"]
