[package]
name = "openxr"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
sys = { package = "openxr-sys", path = "../sys", version = "0.1.0" }
shared_library = "0.1.9"
