[package]
name = "openxr"
description = "OpenXR FFI bindings"
repository = "https://github.com/Ralith/openxrs"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
categories = ["api-bindings", "rendering"]
keywords = ["openxr", "vr"]
license = "MIT/Apache-2.0"
edition = "2018"

[badges]
maintenance = { status = "experimental" }

[features]
loaded = ["shared_library"]
static = ["sys/static", "linked"]
linked = ["sys/prototypes"]
vulkan = ["sys/vulkan", "ash"]
opengl = ["sys/opengl"]
xlib = ["sys/xlib"]
default = ["loaded", "vulkan", "opengl", "xlib"]

[dependencies]
sys = { package = "openxr-sys", path = "../sys", version = "0.1.0", default-features = false }
shared_library = { version = "0.1.9", optional = true }
ash = { version = "0.27", optional = true }
void = "1"
