[package]
name = "openxr"
description = "OpenXR FFI bindings"
repository = "https://github.com/Ralith/openxrs"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
categories = ["api-bindings", "rendering"]
keywords = ["openxr", "vr"]
license = "MIT/Apache-2.0"
edition = "2018"

[badges]
maintenance = { status = "experimental" }

[features]
loaded = ["shared_library"]
static = ["sys/static", "linked"]
linked = ["sys/prototypes"]
ash = ["sys/ash"]
default = ["loaded"]

[dependencies]
sys = { package = "openxr-sys", path = "../sys", version = "0.1.0" }
shared_library = { version = "0.1.9", optional = true }
